MuhtarlikBilgiSistemi1/Controllers/MuhtarHizmetController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuhtarlikBilgiSistemi1.Controllers
{
    public class MuhtarHizmetController : Controller
    {
        // GET: MuhtarHizmet
        HizmetlerManager hm = new HizmetlerManager(new EfHizmetlerDal());
        HizmetlerValidator hizmetlervalidator = new HizmetlerValidator();
       
        // GET: Hizmetler
        public ActionResult Index()
        {
            var HizmetlerValues = hm.GetListHizmet();
            return View(HizmetlerValues);
        }

        [HttpGet]
        public ActionResult AddHizmetler1()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddHizmetler1(Hizmetler entity)
        {
            HizmetlerValidator hizmetlervalidator = new HizmetlerValidator();
            ValidationResult results = hizmetlervalidator.Validate(entity);
            if (results.IsValid)
            {
                hm.HizmetlerAdd(entity);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        //*** MUHTAR GÜNCELLEME***

        [HttpGet]
        public ActionResult UpdateHizmetler1(int id)
        {
            var HizmetlerValues = hm.GetByIdHizmet(id);
            return View(HizmetlerValues);
        }

        [HttpPost]
        public ActionResult UpdateHizmetler1(Hizmetler entity)
        {
            hm.HizmetlerUpdate(entity);
            return RedirectToAction("Index");
        }





    }
}

MuhtarlikBilgiSistemi1/Views/MuhtarHizmet/AddHizmetler1.cshtml
@model EntityLayer.Concrete.Hizmetler
@{
    ViewBag.Title = "AddHizmetler1";
    Layout = "~/Views/Shared/_MuhtarLayout.cshtml";
}

<h2>Ekleme Sayfası</h2>


@using (Html.BeginForm("AddHizmetler1", "MuhtarHizmet", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HizmetId)
        @Html.HiddenFor(x => x.MuhtarId)

        <br />
        @Html.Label("Başlık")
        @Html.TextBoxFor(x => x.Baslik, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Baslik)
        <br />
        @Html.Label("Açıklama")
        @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Aciklama)
        <br />
        <br />
        @Html.Label("Durum")
        @Html.TextAreaFor(x => x.Durum, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Durum)
        <br />
        @Html.Label("Maliyet")
        @Html.TextAreaFor(x => x.Maliyet, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Maliyet)
        <br />
        @Html.Label("Muhtar Adı Soyadı")
        @Html.TextAreaFor(x => x.MuhtarAdiSoyadi, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.MuhtarAdiSoyadi)
        <br />
        @Html.Label("Giriş Tarihi")
        @Html.TextAreaFor(x => x.MuhtarGirisTarihi, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.MuhtarGirisTarihi)
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MuhtarlikBilgiSistemi1/Views/MuhtarHizmet/Index.cshtml
@using EntityLayer.Concrete
@model List<Hizmetler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MuhtarLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        .kutu {
            width: 975px;
            height: 250px;
            border: 1px solid #000;
            background-color: #f8f8ff;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
            </div>
        </div>
    </section>
    <section class="content">
        <!-- Default box -->

        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    <table style="width:75%">

                        @foreach (var item in Model)
                        {

                            <div class="kutu">

                                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                    <div class="card bg-light">

                                        <div class="card-body pt-0">
                                            <div class="row">
                                                <div class="col-7">



                                                    <p class="text-muted text-sm"><b>Başlık: </b>@item.Baslik</p>
                                                    <p class="text-muted text-sm"><b>Açıklama: </b>@item.Aciklama  </p>
                                                    <p class="text-muted text-sm"><b>Durum: </b>@item.Durum </p>
                                                    <p class="text-muted text-sm"><b>Maliyet: </b>@item.Maliyet </p>







                                                </div>
                                            </div>
                                        </div>

                                        <br />
                                        <div class="card-footer">
                                            <div class="text-left">

                                                <a href="/MuhtarHizmet/UpdateHizmetler1/@item.HizmetId" class="btn btn-m  btn-success">
                                                    <i class="fas fa-user"></i>Güncelle


                                                </a>

                                            </div>
                                        </div>
                                    </div>

                                </div>






                                <div class="row">
                                    <div class="col">
                                        <div class="timeline-steps aos-init aos-animate" data-aos="fade-up">
                                            <div class="timeline-step">
                                                <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" @*title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2003"*@>
                                                    <div class="inner-circle"></div>
                                                    <p class="h6 mt-3 mb-1">Gereksinimler</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Muhtar Adı Soyadı:</b>@item.MuhtarAdiSoyadi</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Giriş Tarihi:</b>@item.MuhtarGirisTarihi </p>
                                                </div>
                                            </div>

                                            <div class="timeline-step">
                                                <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" @*title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2004*@>
                                                    <div class="inner-circle"></div>
                                                    <p class="h6 mt-3 mb-1">Devam Ediyor</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Personel Adı Soyadı:</b>@item.DevamEdenPersonelAdiSoyadi</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b> Maliyet Tutarı:</b>@item.MaliyetTutari</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Giriş Tarihi:</b>@item.BelediyeGirisTarihi</p>
                                                </div>
                                            </div>
                                            <div class="timeline-step">
                                                <div class="timeline-content" data-toggle="popover" data-trigger="hover" data-placement="top" @*title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="2005"*@>
                                                    <div class="inner-circle"></div>
                                                    <p class="h6 mt-3 mb-1">Tamamlandı</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Personel Adı Soyadı:</b>@item.TamamlandiPersonelAdiSoyadi</p>
                                                    <p class="h6 text-muted mb-0 mb-lg-0"><b>Bitiş Tarihi:</b>@item.TamamlandiBitisTarihi</p>
                                                </div>
                                            </div>



                                        </div>
                                    </div>
                                </div>


                            </div>
                            <br />


                        }




                    </table>
                </div>
            </div>
        </div>

        @*<a href="/Hizmetler/AddHizmetler/@item.HizmetId" class="btn btn-m  btn-primary">*@
        <a href="/MuhtarHizmet/AddHizmetler1" class="btn btn-primary">Ekle</a>







    </section>


</body>

</html>

MuhtarlikBilgiSistemi1/Views/MuhtarHizmet/UpdateHizmetler1.cshtml
@model EntityLayer.Concrete.Hizmetler
@{
    ViewBag.Title = "UpdateHizmetler1";
    Layout = "~/Views/Shared/_MuhtarLayout.cshtml";
}

<h2>Envanter güncelleme Sayfası</h2>


@using (Html.BeginForm("UpdateHizmetler1", "MuhtarHizmet", FormMethod.Post))
{

    <div class="form-group">

        @Html.HiddenFor(x => x.HizmetId)
        @Html.HiddenFor(x => x.MuhtarId)

        @Html.Label("Başlık:")
        @Html.TextBoxFor(x => x.Baslik, new { @class = "form-control" })
        <br />
        @Html.Label("Açıklama:")
        @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
        <br />
        @Html.Label(" Durum:")
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
        <br />
        @Html.Label("Maliyet:")
        @Html.TextBoxFor(x => x.Maliyet, new { @class = "form-control" })
        <br />
        @Html.Label("Muhtar Adı Soyadı:")
        @Html.TextBoxFor(x => x.MuhtarAdiSoyadi, new { @class = "form-control" })
        <br />
        @Html.Label("Giriş Tarihi:")
        @Html.TextBoxFor(x => x.MuhtarGirisTarihi, new { @class = "form-control" })
        <br /><br />
        <button class="btn btn-success">Kaydet</button>


    </div>
}