MuhtarlikBilgiSistemi1/Controllers/OnemliMekanlarController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuhtarlikBilgiSistemi1.Controllers
{
    public class OnemliMekanlarController : Controller
    {
        // GET: OnemliMekanlar
        OnemliMekanlarManager onemliMekanlarManager = new OnemliMekanlarManager(new EfOnemliMekanlarDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetList()
        {
            var OnemliMekanlarValues = onemliMekanlarManager.GetAll();
            return View(OnemliMekanlarValues);
        }
        
            [HttpGet]
            public ActionResult AddOnemliMekanlar()
            {
                return View();
            }

            [HttpPost]
            public ActionResult AddOnemliMekanlar(OnemliMekanlar entity)
            {
                OnemliMekanlarValidator onemlimekanlarValidator = new OnemliMekanlarValidator();
                ValidationResult results = onemlimekanlarValidator.Validate(entity);
                if (results.IsValid)
                {
                onemliMekanlarManager.AddOnemliMekanlar(entity);
                    return RedirectToAction("GetList");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                }
                return View();
            }
        }
    }

MuhtarlikBilgiSistemi1/Views/OnemliMekanlar/AddOnemliMekanlar.cshtml
@model EntityLayer.Concrete.OnemliMekanlar

@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h1>Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddOnemliMekanlar", "OnemliMekanlar", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x=>x.OnemliMekanlarId)
        @Html.HiddenFor(x=>x.MahalleId)
        <br/>
        @Html.Label("Adı")
        @Html.TextBoxFor(x => x.Adi)
        @Html.ValidationMessageFor(x => x.Adi)
        <br /><br />
        @Html.Label("Yapı Tipi")
        @Html.TextBoxFor(x => x.YapiTipi)
        @Html.ValidationMessageFor(x => x.YapiTipi)
        <br /><br />
        <button>Kaydet</button>
    </div>
}

MuhtarlikBilgiSistemi1/Views/OnemliMekanlar/GetList.cshtml
@using EntityLayer.Concrete
@model List<OnemliMekanlar>

@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Adı</th>
        <th>Yapı Tipi</th>
        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.OnemliMekanlarId</td>
            <td>@item.MahalleId</td>
            <td>@item.Adi</td>
            <td>@item.YapiTipi</td>

        </tr>
    }
</table>
<a href="/OnemliMekanlar/AddOnemliMekanlar" class="btn btn-info">Yeni Kategori</a> 

MuhtarlikBilgiSistemi1/Views/OnemliMekanlar/GetOnemliMekanlarList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetOnemliMekanlarList</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MuhtarlikBilgiSistemi1/Views/OnemliMekanlar/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/Css/bootstrap.min.css" rel="stylesheet" />
<h3>Muhtarlik Bilgi Sistemi-Önemlimekanlar</h3>

<br />
<table class="table table-bordered">
    <tr>

        <th>Adı:</th>
        <th>Yapı Tipi:</th>

    </tr>
    <tr>
        <td>Malatya müzesi</td>
        <td>Betonn</td>
    </tr>
</table>
<button class="btn btn-success">yeni Kategori</button>
<button class="btn btn-danger"> Kategori listesi</button>